// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ShowDescriptionFieldController from "./show_description_field_controller"
application.register("show-description-field", ShowDescriptionFieldController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
